create table if not exists public.decks (
  id bigint generated by default as identity primary key,
  code text unique not null,
  name text not null,
  raw_text text,
  created_at timestamp with time zone not null default now()
);

alter table public.decks add column if not exists id bigint generated by default as identity;
alter table public.decks add column if not exists code text;
alter table public.decks add column if not exists name text;
alter table public.decks add column if not exists raw_text text;
alter table public.decks add column if not exists created_at timestamp with time zone default now();

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'decks'
      and column_name = 'deck_name'
  ) then
    update public.decks
    set name = coalesce(name, deck_name, code)
    where name is null;

    alter table public.decks alter column deck_name drop not null;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'decks'
      and column_name = 'cards'
  ) then
    alter table public.decks alter column cards drop not null;
  end if;
end $$;

update public.decks
set name = coalesce(name, code, 'Untitled')
where name is null;

alter table public.decks alter column code set not null;
alter table public.decks alter column name set not null;

create unique index if not exists decks_code_unique on public.decks(code);
create unique index if not exists decks_id_unique on public.decks(id);

create table if not exists public.cards (
  id bigint generated by default as identity primary key,
  deck_id bigint not null references public.decks(id) on delete cascade,
  front text not null,
  back text not null,
  position integer not null default 0,
  created_at timestamp with time zone not null default now()
);

create index if not exists cards_deck_id_position_idx on public.cards(deck_id, position);

alter table public.decks enable row level security;
alter table public.cards enable row level security;

drop policy if exists "Public decks are readable by code" on public.decks;
drop policy if exists "Public cards are readable by deck" on public.cards;

create policy "Public decks are readable by code"
on public.decks
for select
using (true);

create policy "Public cards are readable by deck"
on public.cards
for select
using (true);
